theme: jekyll-theme-architect
name: Peoples Online Republic
title: People's Online Republic
description: People's Online Republic is a thought experiment that may eventually materialize as an actual online presence. At this phase we are looking for feedback and validation before proceeding.